[package]
name = "rustls"
version = "0.13.1"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"
categories = ["network-programming", "cryptography"]

[dependencies]
untrusted = "0.6.2"
base64 = "0.9"
log = { version = "0.4.0", optional = true }
ring = { version = "0.13.5" }
webpki = "0.18.1"
sct = "0.4"

[features]
default = ["logging"]
logging = ["log"]
dangerous_configuration = []
quic = []

[dev-dependencies]
log = "0.4"
env_logger = "0.5"
mio = "0.6"
docopt = "1.0"
serde = "1.0"
serde_derive = "1.0"
webpki-roots = "0.15.0"
ct-logs = "0.4"
regex = "1.0"
vecio = "0.1"

[[example]]
name = "bogo_shim"
path = "examples/internal/bogo_shim.rs"
required-features = ["dangerous_configuration", "quic"]

[[example]]
name = "trytls_shim"
path = "examples/internal/trytls_shim.rs"

[[example]]
name = "bench"
path = "examples/internal/bench.rs"

[[example]]
name = "tlsclient"
path = "examples/tlsclient.rs"

[[example]]
name = "tlsserver"
path = "examples/tlsserver.rs"

[[example]]
name = "simpleclient"
path = "examples/simpleclient.rs"
